### ISSUE TITLE
Brush up README for 1.0.x

### ISSUE THREAD

**Issue by TentaShion** [TentaShion/AndroidPreparation#36]
## ToDo
* [x] add a description for mail launcher
* [x] add a description for map launcher
* [x] add a description for phone launcher
* [x] add a description for setup
* [x] add a description for web browser launcher
